"""Reference data: the odds tables and the default catalogue.

The bot is useless on an empty database — Summon-bot's first run crashed in ``/shop``
because ``characters`` was empty, and its owners had to hand-insert rows. So a fresh
install seeds itself with:

* the 18-tier ``rarity_chances`` / ``claim_list`` rows (weights come from
  :class:`waifu.enums.Rarity`, i.e. the reference bot's published rates — one source,
  no drift between odds and pricing);
* the shipped catalogue in ``waifu/data/characters.seed.json`` (177 characters across
  every tier, generated by ``scripts/build_catalogue.py``);
* the default items/shop config lives in settings, not here.

Everything is idempotent and ORM-based (raw SQL with a ``::json`` cast worked on
Postgres and broke every test run on SQLite, which is how the reference bot's seeding
script became one-shot). Existing rows are never overwritten: owner edits win.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import func, insert, select, update
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, AsyncSession

from waifu.db.models import Character, ClaimChance, RarityChance
from waifu.enums import Rarity
from waifu.logging import get_logger

log = get_logger("db.seed")

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CHARACTER_FILE = DATA_DIR / "characters.seed.json"

#: Pull odds per tier, in percent of total weight (derived, so it can't disagree with
#: the ladder). ``Rarity.weight`` is the reference bot's per-10 000 value.
TOTAL_WEIGHT = sum(rarity.weight for rarity in Rarity)
TOTAL_CLAIM = sum(rarity.claim_weight for rarity in Rarity)

DEFAULT_ODDS: dict[int, float] = {int(r): round(100.0 * r.weight / TOTAL_WEIGHT, 4) for r in Rarity}
DEFAULT_CLAIM_ODDS: dict[int, float] = {
    int(r): round(100.0 * r.claim_weight / TOTAL_CLAIM, 4) for r in Rarity
}


def catalogue_rows() -> list[dict[str, Any]]:
    """The shipped JSON, or ``[]`` if the file is missing (broken wheel, not a crash)."""
    if not CHARACTER_FILE.exists():  # pragma: no cover - shipped in the package
        log.error("catalogue file missing: %s", CHARACTER_FILE)
        return []
    try:
        raw = json.loads(CHARACTER_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        log.error("catalogue file unreadable (%s): %s", CHARACTER_FILE.name, exc)
        return []
    return [row for row in raw if isinstance(row, dict)]


# ------------------------------------------------------------------------------ odds
async def ensure_odds(conn: AsyncConnection, *, reset: bool = False) -> dict[str, int]:
    """Insert (or with ``reset``, overwrite) the per-rarity odds for all 18 tiers.

    Missing rows are inserted, existing ones are left alone: an owner's ``/chance``
    tuning must survive an upgrade. The reference bot's bootstrap re-inserted the
    defaults on every deploy, which quietly un-did each server's configured rates.
    """
    written = {"rarity_chances": 0, "claim_list": 0}
    for model, key, source in (
        (RarityChance, "rarity_chances", DEFAULT_ODDS),
        (ClaimChance, "claim_list", DEFAULT_CLAIM_ODDS),
    ):
        existing = set((await conn.execute(select(model.rarity_id))).scalars())
        for rarity_id, chance in source.items():
            rarity = Rarity.from_value(rarity_id)
            if rarity_id in existing:
                if reset:
                    await conn.execute(
                        update(model)
                        .where(model.rarity_id == rarity_id)
                        .values(chance=chance, is_enabled=chance > 0)
                    )
                continue
            values: dict[str, Any] = {
                "rarity_id": rarity_id,
                "rarity_name": rarity.label,
                "chance": chance,
            }
            if model is RarityChance:
                values["min_price"] = rarity.base_price
                values["is_enabled"] = True
            await conn.execute(insert(model.__table__).values(**values))
            written[key] += 1
    return written


# ------------------------------------------------------------------------ characters
async def ensure_characters(conn: AsyncConnection, *, force: bool = False) -> dict[str, int]:
    """Insert the shipped catalogue. Returns ``{inserted, skipped, total}``.

    Conflict detection loads the existing ``(name, anime)`` pairs once instead of
    relying on ``ON CONFLICT``, because this runs on SQLite in tests and Postgres in
    production and the two spell upserts differently.
    """
    rows = catalogue_rows()
    if not rows:
        return {"inserted": 0, "skipped": 0, "total": 0}
    existing: set[tuple[str, str]] = (
        set()
        if force
        else {
            (name, anime)
            for name, anime in (await conn.execute(select(Character.name, Character.anime))).all()
        }
    )
    now = datetime.now(UTC).replace(tzinfo=None)
    payloads: list[dict[str, Any]] = []
    for entry in rows:
        key = (str(entry.get("name", "")), str(entry.get("anime", "")))
        if not key[0] or key in existing:
            continue
        rarity = Rarity.from_value(entry.get("rarity_id", 1))
        existing.add(key)
        payloads.append(
            {
                "name": entry["name"],
                "anime": entry.get("anime", ""),
                "rarity": rarity.badge,
                "rarity_id": int(rarity),
                "price": int(entry.get("price") or rarity.base_price),
                "stat_power": int(entry.get("stat_power") or 10 * int(rarity)),
                "description": entry.get("description", ""),
                "voice_line": entry.get("voice_line", ""),
                "persona": entry.get("persona", ""),
                "tags": entry.get("tags", ""),
                "is_active": True,
                "banner_weight": float(entry.get("banner_weight", 1.0) or 1.0),
                "photo_file_id": entry.get("photo_file_id", ""),
                "image_url": entry.get("image_url", ""),
                "video_file_id": entry.get("video_file_id", ""),
                "video_url": entry.get("video_url", ""),
                "sticker_file_id": entry.get("sticker_file_id", ""),
                "meta": entry.get("meta") or {},
                "created_at": now,
                "updated_at": now,
            }
        )
    if payloads:
        # Batched: 177 single inserts is a slow first boot, one executemany is not.
        for chunk in (payloads[i : i + 80] for i in range(0, len(payloads), 80)):
            await conn.execute(insert(Character.__table__), chunk)
    total = int((await conn.execute(select(func.count()).select_from(Character))).scalar_one() or 0)
    return {"inserted": len(payloads), "skipped": len(rows) - len(payloads), "total": total}


# ------------------------------------------------------------------------------ glue
async def seed_all(
    engine: AsyncEngine, *, characters: bool = True, force: bool = False, reset_odds: bool = False
) -> dict[str, Any]:
    """Called by ``waifu seed``, ``waifu migrate`` and the first-run path in ``waifu doctor``."""
    out: dict[str, Any] = {}
    async with engine.begin() as conn:
        out["odds"] = await ensure_odds(conn, reset=reset_odds)
        if characters:
            out["characters"] = await ensure_characters(conn, force=force)
    if out.get("characters", {}).get("inserted"):
        log.info("seeded %s characters", out["characters"]["inserted"])
    return out


async def seed_session(
    session: AsyncSession, *, characters: bool = True, force: bool = False
) -> dict[str, Any]:
    """Same as :func:`seed_all` but inside a caller's transaction (used by tests)."""
    out: dict[str, Any] = {}
    if characters:
        existing = {
            (name, anime)
            for name, anime in (
                await session.execute(select(Character.name, Character.anime))
            ).all()
        }
        inserted = 0
        for entry in catalogue_rows():
            key = (str(entry.get("name", "")), str(entry.get("anime", "")))
            if not key[0] or (key in existing and not force):
                continue
            rarity = Rarity.from_value(entry.get("rarity_id", 1))
            session.add(
                Character(
                    name=entry["name"],
                    anime=entry.get("anime", ""),
                    rarity=rarity.badge,
                    rarity_id=int(rarity),
                    price=int(entry.get("price") or rarity.base_price),
                    stat_power=int(entry.get("stat_power") or 10 * int(rarity)),
                    description=entry.get("description", ""),
                    voice_line=entry.get("voice_line", ""),
                    tags=entry.get("tags", ""),
                    is_active=True,
                    banner_weight=float(entry.get("banner_weight", 1.0)),
                    image_url=entry.get("image_url", ""),
                )
            )
            inserted += 1
        await session.flush()
        out["characters"] = {
            "inserted": inserted,
            "total": int(
                (await session.execute(select(func.count()).select_from(Character))).scalar_one()
                or 0
            ),
        }
    return out


async def status(engine: AsyncEngine) -> dict[str, int]:
    """What ``waifu doctor`` prints: is the bot playable right now?"""
    async with engine.connect() as conn:
        return {
            "characters": int(
                (await conn.execute(select(func.count()).select_from(Character))).scalar_one() or 0
            ),
            "rarity_rows": int(
                (await conn.execute(select(func.count()).select_from(RarityChance))).scalar_one()
                or 0
            ),
            "claim_rows": int(
                (await conn.execute(select(func.count()).select_from(ClaimChance))).scalar_one()
                or 0
            ),
            "expected_characters": len(catalogue_rows()),
        }


async def reset_odds_to_defaults(conn: AsyncConnection) -> int:
    """Owner command (``/chance --reset``): restore the documented rates."""
    await ensure_odds(conn, reset=True)
    return len(DEFAULT_ODDS)
