"""The reference audit: the extraction document and the map behind it must stay true.

``docs/SUMMON_EXTRACT.md`` is generated from a clone of the reference repo, so CI cannot rebuild it
(no clone, no ``xdis`` in the test env). What CI *can* do is check the claims it makes:

* every module the map names exists in the reference inventory the document lists, and vice versa
  — a module nobody mapped is exactly the failure mode this whole exercise exists to prevent;
* every path the map points at as "where it went here" **exists in this repository** — an audit
  that cites a deleted file is worse than no audit;
* the statuses are from the agreed vocabulary, so the totals line stays comparable between runs.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
MAP_PATH = ROOT / "scripts" / "summon_port_map.json"
DOC_PATH = ROOT / "docs" / "SUMMON_EXTRACT.md"

KNOWN_STATUSES = {"ported", "adapted", "superseded", "tooling", "gap"}


def _map() -> dict:
    return json.loads(MAP_PATH.read_text(encoding="utf-8"))


def _document() -> str:
    assert DOC_PATH.is_file(), f"{DOC_PATH} is generated by `make extract` and must be committed"
    return DOC_PATH.read_text(encoding="utf-8")


def test_the_map_covers_every_module_the_reference_has() -> None:
    doc = _document()
    rows = re.findall(
        r"^\| `([a-z0-9_]+)` \| (ported|adapted|superseded|tooling|gap|\*\*unmapped\*\*)", doc, re.M
    )
    assert len(rows) >= 25, f"the port map table looks truncated: {len(rows)} rows"
    listed = {name for name, _status in rows}
    mapped = set(_map()["modules"])
    assert listed - mapped == set(), "the document lists a module the map does not know"
    # The reverse direction is the point: a new module upstream must show up as unmapped in the
    # document, and an unmapped module must fail here rather than in somebody's feature review.
    unmapped = listed - mapped
    orphaned = mapped - listed
    assert not unmapped and not orphaned


@pytest.mark.parametrize(
    "module", sorted(json.loads(MAP_PATH.read_text(encoding="utf-8"))["modules"])
)
def test_every_map_entry_is_honest(module: str) -> None:
    entry = _map()["modules"][module]
    assert entry["status"] in KNOWN_STATUSES, f"{module}: unknown status {entry['status']!r}"
    assert entry["note"].strip(), f"{module}: an empty note is not an audit"
    where = entry.get("where") or []
    if entry["status"] == "gap":
        return
    assert where, f"{module}: claimed as {entry['status']!r} but points at nothing"
    for path in where:
        target = ROOT / path
        if target.is_dir():
            assert any(target.glob("**/*.py")), f"{module}: {path} has no code in it"
            continue
        assert target.is_file(), f"{module}: {path} does not exist (map drift)"


def test_the_function_inventory_is_not_silently_empty() -> None:
    doc = _document()
    totals = re.search(r"\*\*(\d+) modules\*\*, \*\*(\d+) functions\*\*", doc)
    assert totals, "the header line with the counts is missing"
    modules, functions = (int(value) for value in totals.groups())
    assert modules >= 25 and functions >= 280, (
        f"{modules} modules / {functions} functions — the extractor read the source but not the "
        "bytecode, or the clone moved; re-run `make extract` and check xdis is installed"
    )
    assert "functions present only in bytecode" in doc


def test_the_upload_port_is_recorded_as_the_reference_says() -> None:
    """The one claim the user cares most about has to be in the document, in words."""
    doc = _document().lower()
    assert "upload_character" in doc, "the extraction must name the function it ported"
    assert "only in the bytecode" in doc or "bytecode only" in doc
    assert "temp storage" in doc, "the source's URL-only comment is the evidence; quote it"


def test_api_routes_advertised_in_the_docs_exist() -> None:
    from waifu.api.server import ROUTES

    doc = _document() + (ROOT / "docs" / "API.md").read_text(encoding="utf-8")
    for path, _handler, _method in ROUTES:
        plain = path.split("{")[0]
        assert plain in doc, f"{plain} is served but documented nowhere"


def test_docs_are_linked_from_the_readme() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for name in (
        "SUMMON_EXTRACT.md",
        "API.md",
        "COMMANDS.md",
        "SUMMON_PARITY.md",
        "NEW_BOT_API.md",
    ):
        assert name in readme, f"docs/{name} is unreachable from the README"
