#!/usr/bin/env python3
"""Generate ``docs/COMMANDS.md`` and ``docs/SUMMON_PARITY.md`` from the running bot.

Hand-written reference docs are the reason the reference deployment's help text described
commands that had been renamed two releases earlier. Both files here are derived from the
same registry the dispatcher uses (:func:`waifu.core.dp.public_commands`) plus the parity
contract in ``tests/test_summon_parity.py``, so the only way to make the docs lie is to
make the bot lie first.

Usage::

    python scripts/gen_reference_docs.py            # write both files
    python scripts/gen_reference_docs.py --check     # fail if they are stale (CI)
"""

from __future__ import annotations

import argparse
import importlib
import os
import sys
from pathlib import Path

# Reading defaults is not "running the bot", so the test-mode flag is set for the
# runtime validation (Redis/Postgres are not needed to print a table of constants).
os.environ.setdefault("WAIFU_TEST_MODE", "1")

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

COMMANDS_DOC = ROOT / "docs" / "COMMANDS.md"
PARITY_DOC = ROOT / "docs" / "SUMMON_PARITY.md"

HEADER = (
    "<!-- GENERATED by scripts/gen_reference_docs.py — do not edit. "
    "Run `make docs` (or the script) after adding or renaming a command. -->\n"
)

INTRO = """# Command reference

Every command the bot actually listens for, read out of the routers at generation time.
Descriptions are the handler docstrings, so the first line of a handler's docstring is
user-facing text — write it like UI copy.

Two rules the code follows and this file reflects:

* **no command is claimed twice** — aiogram stops at the first matching handler, so a
  duplicate name is a dead command rather than an error (enforced by
  `tests/test_plugin_registry.py`);
* **aliases are free, names are not** — the reference bot's spellings are kept as aliases
  where they collide with nothing, so muscle memory from the old bot keeps working.
"""

PARITY_INTRO = """# Summon-bot parity

The promise this rewrite was built against: **the same commands and the same collection
pages as `Beasgohan-code/Summon-bot`, with new features on top instead of in place of
them**, and no placeholder data.

Two things in this file are generated; one is a decision:

* the command table below comes from `tests/test_summon_parity.py` (the contract) and the
  live router registry (what is wired);
* the constants table comes from `waifu/settings.py`, whose defaults are the numbers in
  Summon-bot's `config.py`;
* the only *different* spellings are listed under "renamed", each with the reason. If you
  disagree with one, change the alias — not the reason.
"""


def _commands_by_router() -> dict[str, list[tuple[str, str, bool]]]:
    from waifu.core.dp import PLUGIN_ROUTERS, _handler_doc, command_names, walk_routers

    grouped: dict[str, list[tuple[str, str, bool]]] = {}
    for path in PLUGIN_ROUTERS:
        module = importlib.import_module(path)
        root = getattr(module, "router", None)
        if root is None:
            continue
        for router in walk_routers(root):
            for handler in router.message.handlers:
                names = command_names(handler)
                if not names:
                    continue
                grouped.setdefault(str(router.name or "?"), []).append(
                    (names[0], _handler_doc(handler), len(names) > 1 and names[1] != names[0])
                )
    return grouped


def _all_names() -> set[str]:
    from waifu.core.dp import public_commands

    return set(public_commands())


def render_commands() -> str:
    grouped = _commands_by_router()
    lines = [HEADER, INTRO, ""]
    total = 0
    for plugin, rows in grouped.items():
        lines.append(f"## `{plugin}.py`")
        lines.append("")
        lines.append("| command | description |")
        lines.append("| --- | --- |")
        for name, doc, _alias in sorted(rows):
            total += 1
            lines.append(f"| `/{name}` | {doc or '—'} |")
        lines.append("")
    lines.insert(3, f"**{total} commands across {len(grouped)} plugins.**\n")
    return "\n".join(lines) + "\n"


def render_parity() -> str:
    sys.path.insert(0, str(ROOT))
    from tests.test_summon_parity import RENAMED, SUMMON_COMMANDS

    wired = _all_names()
    lines = [HEADER, PARITY_INTRO, ""]
    lines.append("## Commands")
    lines.append("")
    lines.append(
        f"Reference surface: **{len(SUMMON_COMMANDS)} names and aliases**. Wired here: "
        f"**{sum(1 for name in SUMMON_COMMANDS if name in wired)}**."
    )
    lines.append("")
    lines.append("| Summon-bot | status here | what it does |")
    lines.append("| --- | --- | --- |")
    for name, description in sorted(SUMMON_COMMANDS.items()):
        if name in wired:
            status = "✅ wired"
        elif name in RENAMED:
            status = f"🔀 renamed → {RENAMED[name]}"
        else:
            status = "❌ missing"
        lines.append(f"| `/{name}` | {status} | {description} |")
    lines.append("")
    lines.append("## Renamed, and why")
    lines.append("")
    for name, reason in sorted(RENAMED.items()):
        lines.append(f"* `/{name}` — {reason}")
    lines.append("")
    lines.append("## Numbers copied from `config.py`")
    lines.append("")
    lines.append("These are the reference bot's constants, kept as the defaults so an existing")
    lines.append("group notices no economic change on cutover. Each is an environment variable,")
    lines.append("so changing one is a config edit and not a code change.")
    lines.append("")
    from waifu.settings import Settings

    cfg = Settings(_env_file=None, bot_token="1:x", owner_id=1)
    keys = [
        "starting_balance",
        "daily_reward_min",
        "daily_reward_max",
        "spin_min",
        "spin_max",
        "spin_bonus_min",
        "spin_bonus_max",
        "spin_lucky_chance",
        "pull_cost",
        "ten_pull_cost",
        "ten_pull_guarantee_rarity_id",
        "dupe_payout_percent",
        "shop_refresh_cost",
        "auction_fee_percent",
        "spawn_default_limit",
        "spawn_claim_window",
        "guess_timeout_seconds",
        "guess_reward_coins",
        "spam_limit_per_minute",
        "steal_max_percent",
        "pity_high_after",
        "pity_celestial_after",
        "premium_sub_stars",
        "premium_claim_boost_percent",
    ]
    lines.append("| setting | default | env var |")
    lines.append("| --- | --- | --- |")
    for key in keys:
        if not hasattr(cfg, key):
            continue
        value = getattr(cfg, key)
        if isinstance(value, float):
            value = f"{value:g}"
        lines.append(f"| `{key}` | {value} | `WAIFU_{key.upper()}` |")
    lines.append("")
    lines.append("## Roster and odds")
    lines.append("")
    from waifu.db.seed import DEFAULT_CLAIM_ODDS, DEFAULT_ODDS
    from waifu.enums import Rarity

    lines.append("The 18-tier ladder is the reference bot's, including the emoji, the label,")
    lines.append("the base price of each tier and the two independent weights (gacha vs free")
    lines.append("claim). `waifu/data/characters.seed.json` ships the roster the collection")
    lines.append("pages browse, so a fresh install is not an empty database.")
    lines.append("")
    lines.append("| tier | drop % | claim % | base price |")
    lines.append("| --- | --- | --- | --- |")
    for rarity in Rarity:
        lines.append(
            f"| {rarity.emoji} {rarity.label} | {DEFAULT_ODDS.get(int(rarity.value), 0):.2f} | "
            f"{DEFAULT_CLAIM_ODDS.get(int(rarity.value), 0):.2f} | {rarity.base_price:,} |"
        )
    lines.append("")
    lines.append("## Bringing your data across")
    lines.append("")
    lines.append("```bash")
    lines.append("# 1. schema + shipped catalogue")
    lines.append("python -m waifu migrate")
    lines.append("")
    lines.append("# 2. your Summon-bot database (sqlite file, or a postgres URL)")
    lines.append("python -m waifu import-legacy ./summon.db --dry-run   # read-only report first")
    lines.append("python -m waifu import-legacy ./summon.db")
    lines.append("```")
    lines.append("")
    lines.append("The importer covers all 24 legacy tables — wallets, collections, favourites,")
    lines.append("escrow, market listings, codes, boosts — and is idempotent, so a re-run updates")
    lines.append("changed rows instead of duplicating them. Rows it cannot map are reported, not")
    lines.append("invented. See `scripts/import_summon.py`.")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated files are stale"
    )
    args = parser.parse_args()
    wanted = {COMMANDS_DOC: render_commands(), PARITY_DOC: render_parity()}
    stale = []
    for path, body in wanted.items():
        current = path.read_text() if path.exists() else ""
        if current == body:
            continue
        stale.append(path.name)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
            print(f"wrote {path.relative_to(ROOT)}")
    if args.check and stale:
        print(f"stale docs: {', '.join(stale)} — run `python scripts/gen_reference_docs.py`")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
